export const CityListUpdate = ["TOKYO,JP",
"JAKARTA,ID",
"New York ,US",
"SEOUL,KR",
"MANILA,PH",
"Mumbai ,IN",
"Sao Paulo,BR",
"MEXICO CITY,MX",
"Delhi,IN",
"Osaka,JP",
"CAIRO,EG",
"Kolkata ,IN",
"Los Angeles ,US",
"Shanghai,CN",
"MOSCOW,RU",
"BEIJING ,CN",
"BUENOS AIRES,AR",
"Guangzhou,CN",
"Shenzhen,CN",
"Istanbul,TR",
"Rio de Janeiro,BR",
"PARIS,FR",
"Karachi,PK",
"Nagoya,JP",
"Chicago,US",
"Lagos,NG",
"LONDON,GB",
"BANGKOK,TH",
"KINSHASA,CD",
"TEHRAN,IR",
"LIMA,PE",
"Dongguan,CN",
"BOGOTA,CO",
"Chennai,IN",
"DHAKA,BD",
"Essen,DE",
"Tianjin,CN",
"HONG KONG,CN",
"Taipei,CN",
"Lahore,PK",
"Ho Chi Minh City ,VN",
"Bangalore,IN",
"Hyderabad,IN",
"Johannesburg,ZA",
"BAGHDAD,IQ",
"Toronto,CA",
"SANTIAGO,CL",
"KUALA LUMPUR,MY",
"San Francisco ,US",
"Philadelphia ,US",
"Wuhan,CN",
"Miami ,US",
"Dallas ,US",
"MADRID,ES",
"Ahmedabad,IN",
"Boston ,US",
"Belo Horizonte,BR",
"KHARTOUM,SD",
"Saint Petersburg ,RU",
"Shenyang,CN",
"Houston ,US",
"Pune,IN",
"RIYADH,SA",
"SINGAPORE,SG",
"WASHINGTON ,US",
"Yangon ,MM",
"Milan ,IT",
"Atlanta ,US",
"Chongqing,CN",
"Alexandria,EG",
"Nanjing ,CN",
"Guadalajara,MX",
"Barcelona,ES",
"Chengdu,CN",
"Detroit ,US",
"ANKARA,TR",
"ATHENS,GR",
"BERLIN,DE",
"Sydney,AU",
"Monterrey,MX",
"Phoenix ,US",
"Busan ,KR",
"Recife,BR",
"Bandung,ID",
"Porto Alegre,BR",
"Melbourne,AU",
"LUANDA,AO",
"Hangzhou,CN",
"ALGIERS,DZ",
"Hà Noi ,VN",
"Montréal,CA",
"Xi'an,CN",
"PYONGYANG,KP",
"Qingdao,CN",
"Surat,IN",
"Fortaleza,BR",
"Medellín,CO",
"Durban,ZA",
"Kanpur,IN",
"ADDIS ABABA,ET",
"NAIROBI,KE",
"Jeddah,SA",
"Naples,IT",
"KABUL,AF",
"Salvador,BR",
"Harbin,CN",
"Kano,NG",
"Casablanca,MA",
"CAPE TOWN,ZA",
"Curitiba,BR",
"Surabaya,ID",
"San Diego ,US",
"Seattle ,US",
"ROME,IT",
"Dar es Salaam,TZ",
"Taichung,CN",
"Jaipur,IN",
"CARACAS,VE",
"DAKAR,SN",
"Kaohsiung,CN",
"Minneapolis ,US",
"Lucknow,IN",
"AMMAN,JO",
"Tel Aviv-Yafo,IL",
"Guayaquil,EC",
"KYIV ,UA",
"Faisalabad ,PK",
"Mashhad,IR",
"Izmir,TR",
"Rawalpindi,PK",
"TASHKENT,UZ",
"Katowice,PL",
"Changchun,CN",
"Campinas,BR",
"Daegu ,KR",
"Changsha,CN",
"Nagpur,IN",
"San Juan,PH",
"Aleppo,SY",
"LISBON,PT",
"Frankfurt am Main,DE",
"Nanchang,CN",
"Birmingham[] ,GB",
"Tampa ,US",
"Medan,ID",
"Dalian,CN",
"TUNIS,TN",
"Shijiazhuang,CN",
"Manchester,GB",
"PORT-AU-PRINCE,HT",
"DAMASCUS,SY",
"Ji'nan,CN",
"Fukuoka,JP",
"SANTO DOMINGO,DO",
"HAVANA,CU",
"Cali,CO",
"Denver ,US",
"St. Louis ,US",
"Colombo,BR",
"Dubai,AE",
"Baltimore ,US",
"Sapporo,JP",
"Rotterdam,NL",
"Vancouver,CA",
"Preston,GB",
"Patna,IN",
"SANA'A,YE",
"WARSAW,PL",
"Bonn,DE",
"ACCRA,GH",
"BUCHAREST,RO",
"Yokohama,JP",
"Kunming,CN",
"Guiyang,CN",
"Zibo,CN",
"Incheon,KR",
"Zhengzhou,CN",
"Taiyuan,CN",
"Chaoyang ,CN",
"BRASILIA,BR",
"Zhongshan,CN",
"West Midlands,GB",
"Giza,EG",
"Quezon City,PH",
"Nanhai,CN",
"Fuzhou,CN",
"Lanzhou,CN",
"Xiamen,CN",
"Chittagong,BD",
"Zaozhuang,CN",
"Jilin,CN",
"Linyi,CN",
"Wenzhou,CN",
"STOCKHOLM,SE",
"Puebla de Zaragoza,MX",
"Puning,CN",
"BAKU,AZ",
"Ibadan,NG",
"Brisbane,AU",
"MINSK,BY",
"Sikasso,ML",
"Nanchong,CN",
"Nanning,CN",
"Urumqi,CN",
"Yantai,CN",
"Fuyang,CN",
"Tangshan,CN",
"Maracaibo,VE",
"Hamburg,DE",
"BUDAPEST,HU",
"Shunde,CN",
"Manaus,BR",
"Xuzhou,CN",
"Ségou,ML",
"Baotou,CN",
"Hefei,CN",
"VIENNA,AT",
"Indore,IN",
"ASUNCION,PY",
"Tianmen,CN",
"BELGRADE,RS",
"Suzhou,CN",
"Suizhou,CN",
"Nanyang,CN",
"Nakuru,KE",
"Koulikoro,ML",
"Ningbo,CN",
"Liuan,CN",
"Anshan,CN",
"Tengzhou,CN",
"Qiqihaer,CN",
"Pizhou,CN",
"Taian,CN",
"Datong,CN",
"Kobe,JP",
"Hama,SY",
"Esfahan,IR",
"TRIPOLI,LY",
"West Yorkshire,GB",
"Vadodara,IN",
"Luoyang,CN",
"QUITO,EC",
"Jinjiang,CN",
"Mopti,ML",
"Perth,AU",
"Daejeon ,KR",
"Kyoto,JP",
"Xiantao,CN",
"Tangerang,ID",
"Bhopal,IN",
"Coimbatore,IN",
"Kharkiv,UA",
"Gwangju ,KR",
"Xinghua,CN",
"HARARE,ZW",
"Fushun,CN",
"Shangqiu,CN",
"Belém,BR",
"Wuxi,CN",
"Hechuan,CN",
"Wujin,CN",
"Guigang,CN",
"Jianyang ,CN",
"Huhehaote,CN",
"Santa Cruz,BO",
"Semarang,ID",
"Ludhiana,IN",
"Novosibirsk,RU",
"Neijiang,CN",
"MAPUTO,MZ",
"Nan'an,CN",
"Douala,CM",
"Weifang,CN",
"Daqing,CN",
"Kayes,ML",
"Tongzhou,CN",
"Tabriz,IR",
"Homs,SY",
"Rugao,CN",
"Guiping,CN",
"Huainan,CN",
"Kochi,IN",
"Suining,CN",
"Bozhou,CN",
"Zhanjiang,CN",
"Changde,CN",
"MONTEVIDEO,UY",
"Xintai,CN",
"Ekaterinoburg,RU",
"Juárez,MX",
"Handan,CN",
"Visakhapatnam,IN",
"Kawasaki,JP",
"Jiangjin,CN",
"Pingdu,CN",
"Agra,IN",
"Jiangyin,CN",
"Tijuana,MX",
"Liuyang,CN",
"Bursa,TR",
"Al-Hasakeh,SY",
"Makkah,SA",
"YAOUNDE,CM",
"Xuanwei,CN",
"Dengzhou,CN",
"Palembang,ID",
"Nizhny Novgorod,RU",
"León ,MX",
"Guarulhos,BR",
"Heze,CN",
"Auckland,NZ",
"Omdurman,SD",
"Shantou,CN",
"Leizhou,CN",
"Yongcheng,CN",
"Valencia,VE",
"Thane,IN",
"San Antonio ,US",
"Xinyang,CN",
"Luzhou,CN",
"Almaty,KZ",
"Changshu,CN",
"Taixing,CN",
"PHNOM PENH,KH",
"Laiwu,CN",
"Xiaoshan,CN",
"Yiyang,CN",
"Goiânia,BR",
"Liuzhou,CN",
"Gaozhou,CN",
"Cixi,CN",
"Karaj,IR",
"MOGADISHU,SO",
"Varanasi,IN",
"Córdoba,AR",
"KAMPALA,UG",
"Ruian,CN",
"Lianjiang,CN",
"Huaian,CN",
"Shiraz,IR",
"Multan,PK",
"Madurai,IN",
"München,DE",
"Kalyan,IN",
"Quanzhou,CN",
"Adana,TR",
"Bazhong,CN",
"Fès,MA",
"OUAGADOUGOU,BF",
"Haicheng,CN",
"Xishan,CN",
"Leiyang,CN",
"Caloocan,PH",
"Kalookan ,PH",
"Jingzhou,CN",
"Saitama,JP",
"PRAGUE,CZ",
"Fuqing,CN",
"Kumasi,GH",
"Meerut,IN",
"Hyderabad,PK",
"Lufeng,CN",
"Dongtai,CN",
"Yixing,CN",
"Mianyang,CN",
"Wenling,CN",
"Leqing,CN",
"OTTAWA,CA",
"Yushu,CN",
"Barranquilla,CO",
"Hiroshima,JP",
"Chifeng,CN",
"Nashik,IN",
"Makasar ,ID",
"SOFIA,BG",
"Rizhao,CN",
"Davao,PH",
"Tianshui,CN",
"Huzhou,CN",
"Samara ,RU",
"Omsk,RU",
"Gujranwala,PK",
"Adelaide,AU",
"Macheng,CN",
"Wuxian,CN",
"Bijie,CN",
"Yuzhou,CN",
"Leshan,CN",
"La Matanza,AR",
"Rosario,AR",
"Jabalpur,IN",
"Kazan,RU",
"Jimo,CN",
"Dingzhou,CN",
"Calgary,CA",
"YEREVAN,AM",
"El-Jadida,MA",
"Jamshedpur,IN",
"Zürich,CH",
"Zoucheng,CN",
"Pikine-Guediawaye,SN",
"Anqiu,CN",
"Guang'an,CN",
"Chelyabinsk,RU",
"CONAKRY,GN",
"Asansol,IN",
"Shouguang,CN",
"Changzhou,CN",
"Ulsan,KR",
"Zhuji,CN",
"Toluca ,MX",
"Marrakech,MA",
"Dhanbad,IN",
"TBILISI,GE",
"Hanchuan,CN",
"LUSAKA,ZM",
"Qidong,CN",
"Faridabad,IN",
"Zaoyang,CN",
"Zhucheng,CN",
"Rostov-na-Donu,RU",
"Jiangdu,CN",
"Xiangcheng,CN",
"Zigong,CN",
"Jining ,CN",
"Edmonton,CA",
"Allahabad,IN",
"Beiliu,CN",
"Dnipropetrovsk,UA",
"Gongzhuling,CN",
"Qinzhou,CN",
"Ufa,RU",
"Sendai,JP",
"Volgograd,RU",
"Ezhou,CN",
"GUATEMALA CITY,GT",
"Zhongxiang,CN",
"AMSTERDAM,NL",
"BRUSSELS,BE",
"BAMAKO,ML",
"Ziyang,CN",
"ANTANANARIVO,MG",
"Mudanjiang,CN",
"Amritsar,IN",
"Vijayawada,IN",
"Haora ,IN",
"Donetsk,UA",
"Huazhou,CN",
"Fuzhou ,CN",
"Pimpri Chinchwad,IN",
"DUBLIN,IE",
"Rajkot,IN",
"Sao Luís,BR",
"Béni-Mellal,MA",
"Lianyuan,CN",
"Liupanshui,CN",
"Kaduna,NG",
"Kitakyushu,JP",
"Qianjiang,CN",
"Perm,RU",
"Odessa,UA",
"Qom,IR",
"Yongchuan,CN",
"Peshawar,PK",
"Linzhou,CN",
"Benxi,CN",
"ULAANBAATAR,MN",
"Zhangqiu,CN",
"Yongzhou,CN",
"Sao Gonçalo,BR",
"Srinagar,IN",
"Ghaziabad,IN",
"Xinyi ,CN",
"Köln,DE",
"Zhangjiagang,CN",
"Wafangdian,CN",
"Xianyang,CN",
"Liaocheng,CN",
"Ahwaz,IR",
"Taishan,CN",
"Linhai,CN",
"Feicheng,CN",
"Suwon,KR",
"Wuwei,CN",
"Haimen,CN",
"San Luis Potosí,MX",
"Liling,CN",
"Xinhui,CN",
"Gaziantep,TR",
"Krasnoyarsk,RU",
"Chiba,JP",
"Voronezh,RU",
"Durg-Bhilai Nagar,IN",
"Ruzhou,CN",
"Maceió,BR",
"Yichun ,CN",
"Al-Madinah,SA",
"Yulin ,CN",
"Seongnam,KR",
"Yueyang,CN",
"Yiwu,CN",
"San Jose ,US",
"Jixi,CN",
"MANAGUA,NI",
"Xinyi,CN",
"Safi,MA",
"Guangyuan,CN",
"Soweto,ZA",
"Zhangjiakou,CN",
"Baoding,CN",
"Cartagena,CO",
"Huludao,CN",
"Pingdingshan,CN",
"Torino,IT",
"Zengcheng,CN",
"Laiyang,CN",
"Qingzhou,CN",
"Aurangabad,IN",
"Lattakia,SY",
"Mérida,MX",
"Laizhou,CN",
"Thiruvananthapuram,IN",
"Weinan,CN",
"Wuchang,CN",
"Guangshui,CN",
"Gaizhou,CN",
"Göteborg,SE",
"Xiaogan,CN",
"Torreón,MX",
"Jiaxing,CN",
"Kozhikode,IN",
"Salé,MA",
"Zhuzhou,CN",
"Tyneside,GB",
"Hengyang,CN",
"Dehui,CN",
"Honghu,CN",
"Danyang,CN",
"Daye,CN",
"Solapur,IN",
"Xingning,CN",
"Xiangfan,CN",
"Shubra-El-Khema,EG",
"Luoding,CN",
"Gwalior,IN",
"Ranchi,IN",
"Huiyang,CN",
"Mombasa,KE",
"Jinzhou,CN",
"Jiangyan,CN",
"Chenghai,CN",
"Jiamusi,CN",
"Songzi,CN",
"TEGUCIGALPA,HN",
"Wujiang,CN",
"Jodhpur,IN",
"Duque de Caxias,BR",
"Xi'ning,CN",
"Yuyao,CN",
"Hezhou,CN",
"Jiangyou,CN",
"Tiruchchirappalli,IN",
"Baoshan,CN",
"Saratov,RU",
"Nova Iguaçu,BR",
"Ankang,CN",
"Gaomi,CN",
"Yangchun,CN",
"Santiago de los Caballeros,DO",
"Danzhou,CN",
"LA PAZ,BO",
"Zhuanghe,CN",
"Zhuhai,CN",
"Zhaodong,CN",
"Sakai,JP",
"Haikou,CN",
"Jiaonan,CN",
"El Alto,BO",
"Xuancheng,CN",
"Wuchuan,CN",
"Yuhang,CN",
"Qinhuangdao,CN",
"Bogor,ID",
"Kermanshah,IR",
"Longhai,CN",
"Liverpool,GB",
"Yanshi,CN",
"Guwahati,IN",
"Yichun,CN",
"Konya,TR",
"Barquisimeto,VE",
"Yingde,CN",
"Bengbu,CN",
"Yibin,CN",
"Chandigarh,IN",
"Xiangxiang,CN",
"Yinchuan,CN",
"Valencia,ES",
"Guilin,CN",
"Hamamatsu,JP",
"Sao Bernardo do Campo,BR",
"Deir El-Zor,SY",
"BISHKEK,KG",
"Teresina,BR",
"Suihua,CN",
"BENGHAZI,LY",
"Jiutai,CN",
"Meishan,CN",
"Zaporizhya,UA",
"Gaoyou,CN",
"Marseille,FR",
"Kaifeng,CN",
"Changning,CN",
"Tongliao,CN",
"Natal,BR",
"Bandar Lampung,ID",
"Dongying,CN",
"Gaoan,CN",
"Langzhong,CN",
"Lichuan,CN",
"Hubli-Dharwad,IN",
"Mysore,IN",
"Niigata,JP",
"Indianapolis ,US",
"Jiaozhou,CN",
"Pingxiang ,CN",
"Haiphong,VN",
"Arequipa,PE",
"Jacksonville ,US",
"Tanger,MA",
"Dandong,CN",
"KISHINEV,MD",
"Krasnodar,RU",
"ZAGREB,HR",
"Xinmi,CN",
"Chaohu,CN",
"Xinyu,CN",
"Gongyi,CN",
"Huixian,CN",
"Xinxiang,CN",
"Port Elizabeth,ZA",
"Mendoza,AR",
"Nantong,CN",
"Pengzhou,CN",
"Khulna,BD",
"Malang,ID",
"Padang,ID",
"Anyang,CN",
"Renqiu,CN",
"Foshan,CN",
"Anshun,CN",
"Chihuahua,MX",
"Campo Grande,BR",
"Lódz,PL",
"Goyang,KR",
"Benin City,NG",
"Bucheon ,KR",
"Gaocheng,CN",
"Pulandian,CN",
"Hejian,CN",
"Dafeng,CN",
"Kraków,PL",
"Enshi,CN",
"Dongyang,CN",
"Lviv,UA",
"Kunshan,CN",
"Shuangcheng,CN",
"Salem,IN",
"Jiaozuo,CN",
"Ad-Dammam,SA",
"Huaibei,CN",
"Liyang,CN",
"Samut Prakan,TH",
"Rongcheng,CN",
"Cenxi,CN",
"Nampho,KP",
"Columbus ,US",
"Bareilly,IN",
"Leping,CN",
"Laixi,CN",
"Liaoyang,CN",
"Zhaotong,CN",
"JERUSALEM,IL",
"Tainan,CN",
"Cuernavaca,MX",
"RIGA,LV",
"Linfen,CN",
"Québec,CA",
"Lingbao,CN",
"Shangyu,CN",
"Wuan,CN",
"Hailun,CN",
"Xingyi,CN",
"Wuxue,CN",
"Cebu,PH",
"Aguascalientes,MX",
"Tolyatti,RU",
"Hamilton,CA",
"Zhoushan,CN",
"Langfang,CN",
"Osasco,BR",
"Nonthaburi,TH",
"Dashiqiao,CN",
"Tongxiang,CN",
"Yichang,CN",
"Yangzhou,CN",
"Blantyre City,MW",
"Hamhung,KP",
"Jalandhar,IN",
"Al-Rakka,SY",
"NIAMEY,NE",
"Xiangtan,CN",
"Winnipeg,CA",
"Oran,DZ",
"Kota,IN",
"Sevilla,ES",
"Navi Mumbai ,IN",
"Port Harcourt,NG",
"Saltillo,MX",
"Khartoum North,SD",
"Shizuoka,JP",
"Yuanjiang,CN",
"Raipur,IN",
"Kryviy Rig,UA",
"Yingkou,CN",
"Wuhu,CN",
"Zhenjiang,CN",
"Querétaro,MX",
"Nankang,CN",
"Wugang ,CN",
"Hegang,CN",
"Linqing,CN",
"PRETORIA,ZA",
"Zunyi,CN",
"Panzhihua,CN",
"Austin ,US",
"Changle,CN",
"Lianyungang,CN",
"Yancheng,CN",
"Zunhua,CN",
"Changyi,CN",
"Meknès,MA",
"Qiongshan,CN",
"Bulawayo,ZW",
"Wendeng,CN",
"Okayama,JP",
"Santo André,BR",
"RABAT,MA",
"Pakanbaru,ID",
"Nehe,CN",
"Memphis ,US",
"Joao Pessoa,BR",
"KATHMANDU,NP",
"Longkou,CN",
"Shengzhou,CN",
"Antalya,TR",
"Kumamoto,JP",
"LILONGWE,MW",
"Mexicali,MX",
"Kaiping,CN",
"Palermo,IT",
"Aligarh,IN",
"Nottingham,GB",
"Haining,CN",
"Mosul,IQ",
"Hermosillo,MX",
"Tongcheng,CN",
"Shulan,CN",
"Miluo,CN",
"Bhubaneswar,IN",
"Yangquan,CN",
"Chenzhou,CN",
"Haiyang,CN",
"Morelia,MX",
"Huangshi ,CN",
"Xinmin,CN",
"Tétouan,MA",
"Barnaul,RU",
"Qixia,CN",
"Jaboatao dos Guarapes,BR",
"Chongzhou,CN",
"Cotonou,BJ",
"Yingcheng,CN",
"Zaragoza,ES",
"Changzhi,CN",
"Qujing,CN",
"Linghai,CN",
"Changge,CN",
"Trujillo,PE",
"Tampico,MX",
"Maoming,CN",
"Morón,AR",
"La Plata,AR",
"Ciudad Guayana,VE",
"Moradabad,IN",
"Jieshou,CN",
"Sheffield,GB",
"Donggang,CN",
"Jingjiang,CN",
"Acheng,CN",
"Acapulco ,MX",
"Veracruz,MX",
"Ulyanovsk,RU",
"Wroclaw,PL",
"Jieyang,CN",
"Shaoxing,CN",
"Qian'an,CN",
"Nanchuan,CN",
"Qionglai,CN",
"Deyang,CN",
"Sagamihara,JP",
"Fuyang ,CN",
"Fuxin,CN",
"Jiyuan,CN",
"Puente Alto,CL",
"Qufu,CN",
"Gaoyao,CN",
"Gorakhpur,IN",
"Fort Worth ,US",
"Xinji,CN",
"San Miguel de Tucumán,AR",
"Dujiangyan,CN",
"The Hague,NL",
"Bhiwandi,IN",
"Culiacán Rosales,MX",
"Lingyuan,CN",
"Xingyang,CN",
"Maiduguri,NG",
"Genova,IT",
"Meihekou,CN",
"Izhevsk,RU",
"Jeonju ,KR",
"Leling,CN",
"Xichang,CN",
"COLOMBO,LK",
"Zaria,NG",
"Anlu,CN",
"Sao José dos Campos,BR",
"Charlotte ,US",
"Yizheng,CN",
"Malmö,SE",
"Weihai,CN",
"Xinzheng,CN",
"Dengfeng,CN",
"Vladivostok,RU",
"Shaoyang,CN",
"Taizhou,CN",
"Jammu,IN",
"Lanxi,CN",
"Yuncheng,CN",
"Kagoshima,JP",
"Yaroslave,RU",
"Contagem,BR",
"Shishou,CN",
"Panjin,CN",
"Zamboanga,PH",
"Orumiyeh,IR",
"Binzhou,CN",
"Kisumu,KE",
"Baoji,CN",
"Uberlândia,BR",
"El Paso ,US",
"Yunzhou,CN",
"Kénitra,MA",
"Diyarbakir,TR",
"Jurong,CN",
"Cúcuta,CO",
"Zhaoyuan,CN",
"Huizhou,CN",
"Tianchang,CN",
"Dortmund,DE",
"Shihezi,CN",
"Shiyan,CN",
"Cuttack,IN",
"Cochabamba,BO",
"Cheongju,KR",
"Jingmen,CN",
"Shangzhi,CN",
"Anqing,CN",
"Chongjin,KP",
"Stuttgart,DE",
"Rushan,CN",
"KINGSTON,JM",
"Milwaukee ,US",
"Sorocaba,BR",
"Glasgow,GB",
"Khabarovsk,RU",
"Guanghan,CN",
"Warangal,IN",
"Irkutsk,RU",
"Tyumen,RU",
"Lomas de Zamora,AR",
"Beipiao,CN",
"Funabashi,JP",
"Mingguang,CN",
"Düsseldorf,DE",
"Shenzhou,CN",
"Içel,TR",
"Zhangzhou,CN",
"Xianning,CN",
"Maanshan,CN",
"Bandjarmasin,ID",
"Callao,PE",
"Poznan,PL",
"Kayseri,TR",
"Chon Buri,TH",
"Quetta,PK",
"Shuozhou,CN",
"Samarinda,ID",
"HELSINKI,FI",
"Akesu,CN",
"Novokuznetsk,RU",
"Málaga,ES",
"Fengcheng,CN",
"Hachioji,JP",
"Ribeirao Prêto,BR",
"Beihai,CN",
"Jamnagar,IN",
"NOUAKCHOTT,MR",
"Bazhou,CN",
"Yongkang,CN",
"Louisville ,US",
"Chizhou,CN",
"Huaiyin,CN",
"Fuan,CN",
"Bhilai Nagar,IN",
"Dezhou,CN",
"Makhachkala,RU",
"Xingping,CN",
"Jiujiang,CN",
"Bristol,GB",
"Botou,CN",
"Fengnan,CN",
"ASTANA,KZ",
"Yizhou,CN",
"Amravati,IN",
"Nashville-Davidson ,US",
"Batam,ID",
"Orenburg,RU",
"Zhuozhou,CN",
"Las Vegas ,US",
"Cancun,MX",
"Longyan,CN",
"OSLO,NO",
"Cuiabá,BR",
"Tiruppur,IN",
"VILNIUS,LT",
"Bremen,DE",
"Gold Coast-Tweed,AU",
"Gaobeidian,CN",
"Mangalore,IN",
"Songyuan,CN",
"Yangjiang,CN",
"Wanyuan,CN",
"Jiangmen,CN",
"Xingtai,CN",
"Shaoguan,CN",
"Feira de Santana,BR",
"Guixi,CN",
"Ruijin,CN",
"Zahedan,IR",
"Jinzhong,CN",
"Portland ,US",
"Jintan,CN",
"Reynosa,MX",
"Ilorin,NG",
"Oklahoma City ,US",
"Nakhon Ratchasima,TH",
"N'DJAMENA,TD",
"Shangzhou,CN",
"Panshi,CN",
"Kerman,IR",
"Kaiyuan,CN",
"ISLAMABAD,PK",
"SARAJEVO,BA",
"Bikaner,IN",
"DUSHANBE,TJ",
"Dehradun,IN",
"Zhangshu,CN",
"Beining,CN",
"ABU DHABI,AE",
"Shimkent,KZ",
"Xingcheng,CN",
"Imbaba,EG",
"Yicheng,CN",
"SKOPLJE,MK",
"Kadhimain,IQ",
"At-Ta'if,SA",
"Dali,CN",
"Fuding,CN",
"Jinzhou ,CN",
"Renhuai,CN",
"Mira-Bhayandar,IN",
"Kemerovo,RU",
"Duisburg,DE",
"Rasht,IR",
];